server:
  port:
    8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enable: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/accounts_db
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver #com.mysql.cj.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  application:
#    name: Walletwise

#server:
#  port: 8080
#spring:
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#      show-sql: true
#      ddl-auto: update
#  datasource:
#    url: jdbc:postgresql://localhost:5432/microservice
#    username: postgres
#    password: Bellonee_1994
#    driver-class-name: org.postgresql.Driver


